### ISSUE TITLE
output issue

### ISSUE THREAD

**Issue by pavanreddy410** [MasonEdgar/DCT-Image-Steganography#1]
read error displaying :raise ReadError("Reading off the end of the data. "
bitstring.ReadError: Reading off the end of the data. Tried to read 8 bits when only 1 available. please help

**Comment by MasonEdgar** [comment]
Duplicate

**Comment by pavanreddy410** [comment]
sorry to ask but can you be more specific please

**Comment by aksingh44** [comment]
> sorry to ask but can you be more specific please

hey! having the same issue...were you able to debug it?
