### ISSUE TITLE
 Print secret message back to the user

### ISSUE THREAD

**Issue by mukund-sainath** [MasonEdgar/DCT-Image-Steganography#3]
ReadError: Reading off the end of the data. Tried to read 8 bits when only 7  available.

This is the error I am getting when trying to run the extract_stego_imag.py.
Can u please help me with the error?

**Comment by HLee213** [comment]
> ReadError: Reading off the end of the data. Tried to read 8 bits when only 7 available.
> 
> This is the error I am getting when trying to run the extract_stego_imag.py. Can u please help me with the error?

I have the same problem

**Comment by aksingh44** [comment]
> ReadError: Reading off the end of the data. Tried to read 8 bits when only 7 available.
> 
> This is the error I am getting when trying to run the extract_stego_imag.py. Can u please help me with the error?

I have the same problem...did anyone debug it?

**Comment by MasonEdgar** [comment]
Fixed with PR #5
